# Generated by Django 4.0.3 on 2022-03-06 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professor',
            name='department',
            field=models.CharField(choices=[('math', 'Math'), ('english', 'English'), ('science', 'Science'), ('informatics', 'Informatics')], max_length=30),
        ),
    ]
